site_name: Pecano ERP
site_url: https://joramrq.github.io/PecanoDocuments/
site_author: Kedy Joram
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

repo_name: joramrq/PecanoDocuments
repo_url: https://github.com/joramrq/PecanoDocuments
theme:
  name: material
  favicon: imagenes/pecano2.png
  icon:
    logo: material/palm-tree
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - header.autohide
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
    
nav:
  - Inicio: index.md
  - Instalación:
      - General: instalacion.md
      - Para Playa: instalacionplaya.md
  - Configuración: configuracion.md
  - Módulos:
      - Ventas: modulos/ventas.md
      - Compras: modulos/compras.md
      - Contabilidad: modulos/contabilidad.md
      - Logisitica:
        - Reportes: modulos/logistica_reportes.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
   - search
   - include-markdown
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: true

extra_javascript:
  - js/password-generator.js


extra_css:
  - css/extra.css